development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("SCALINGO_REDISCLOUD_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: sports_production
