development:
  cloud_name: "drqqgy0so"
  api_key: "359153571631659"
  api_secret: "vNlM4U5dShW_LxGxJwteCuKeymE"
  secure: true

production:
  cloud_name: "drqqgy0so"
  api_key: "359153571631659"
  api_secret: "vNlM4U5dShW_LxGxJwteCuKeymE"
  secure: true
